spring:
  application:
    name: neurohelp

  datasource:
    url: jdbc:postgresql://localhost:5432/neurohelp
    username: postgres
    password: shiva
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8082

logging:
  level:
    root: INFO
    com.project.neurohelp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} [corr=%X{correlationId}] - %msg%n"

neurohelp:
  ai-service:
    base-url: http://localhost:8000
  jwt:
    issuer: neurohelp
    secret: ###
    access-token-expiration-minutes: 60

